import os
dir_1=os.getcwd()
app_name = input("Enter your app name: ")
cmd_1="mkdir {}".format(app_name)
os.system(cmd_1)
print("Completed creating the {} directory .....".format(app_name))
os.system("sleep 1")
curr_dir=os.getcwd()
os.chdir("{}/{}".format(curr_dir,app_name))
cmd_2="mkdir app"
os.system(cmd_2)
print("Completed creating the app directory .....")
os.system("sleep 1")
cmd_2_1="mkdir templates"
os.system(cmd_2_1)
print("Completed creating the templates directory .....")
os.system("sleep 1")
cmd_3="cp {}/Tool/Docker/Dockerfile .".format(dir_1)
os.system(cmd_3)
print("Completed creating the Dockerfile .....")
os.system("sleep 1")
cmd_4="cp {}/Tool/Kubernetes/deployment.yaml .".format(dir_1)
os.system(cmd_4)
print("Completed creating the deployment.yaml .....")
cmd_6_0="cp {}/Tool/Python/kube_deploy.py .".format(dir_1)
os.system(cmd_6_0)
print("Creating kube_deploy.py .... ")
os.system("mkdir Terraform_Nginx")
print("Created the Terraform_Nginx Directory")
os.chdir("{}/{}/Terraform_Nginx".format(dir_1,app_name))
cmd_6_1="cp {}/Tool/Terraform_Mac_Lin/main.tf .".format(dir_1)
print("Created the main.tf")
os.system(cmd_6_1)
cmd_6_2="cp {}/Tool/Terraform_Mac_Lin/terraform_deploy.py .".format(dir_1)
os.system(cmd_6_2)
print("Created the terraform_deploy.py")
os.system("sleep 1")
os.chdir("{}/{}/app".format(dir_1,app_name))
os.system("sleep 1")
cmd_5="cp {}/Tool/Python/main.py .".format(dir_1)
os.system(cmd_5)
print("Completed creating the main.py .....")
os.system("sleep 1")
cmd_6="touch requirements.txt"
os.system(cmd_6)
print("Completed creating the requirements.txt .....")
os.system("sleep 1")
os.system("sleep 1")
print("Successfully completed your project template...😃")
new_dir="{}/{}".format(curr_dir,app_name)
cmd_7="docker build -f {}/Dockerfile -t hello-python:latest .".format(new_dir)
os.system(cmd_7)
print("Building the docker image....")
cmd_8="docker run -p 5000:5000 hello-python"
os.system(cmd_8)
